### PR TITLE
Add addressType option for Vagrant VSphere plugin

### PR DESCRIPTION
**Pull request by mreuvers**
Hello Stuart,

I have added an addressType option for the vsphere plugin. With vsphere 5.5 it turned out to be necessary to put the addressType of the network card to Manual in order to set a custom mac address on it. I would appreciate if this could be merged into the next release.

Thank you,
Martijn

### CODE REVIEW

**Comment by michaeljb** [comment]
Hi @mreuvers,

As you may have noticed, the [Travis CI build](https://travis-ci.org/nsidc/vagrant-vsphere/builds/51982326) is failing due to some RuboCop violations. If you could make the necessary changes to get RuboCop and unit tests passing (which you can check by simply running `rake`), that would be great.

A couple violations can probably be fixed by running `rubocop --auto-correct`. For the complexity and line-length related cops, it's fine to [regenerate the todo configuration](https://github.com/bbatsov/rubocop#automatically-generated-configuration); just make sure no new cops are added to the todo file.

Thanks,
Michael

**Comment by michaeljb** [comment]
I rebased your change onto `nsidc:master`, and I was able to fix the RuboCop violations without much trouble in d558f72 (on a new branch, `address-type`. However, there are still test failures caused by your change; see [this Travis-CI build](https://travis-ci.org/nsidc/vagrant-vsphere/builds/71993972).

If you could start from the `address-type` branch and get the tests working, that would be great.

**Comment by mreuvers** [comment]
Hello, 

Apologies for not replying earlier, I was on holidays and I had missed your message. Thank you for reply.

I originally made this change on another branch, but that person never did anything with my pull request. So much later I decided to it on the master (yours) instead. I guess that's why there are so many differences as it was added on way older code.

I found this link: https://github.com/nsidc/vagrant-vsphere/blob/master/DEVELOPMENT.md on your site. I am happy to try fix this, but I am no ruby coder myself. Can you maybe quickly point or tell me, what I should have in order to actually run the tests (I am on an ubuntu flavour) locally, so I can actually try fixing them.

Thanks!

**Comment by michaeljb** [comment]
>  I guess that's why there are so many differences as it was added on way older code.

Looks like this was case. Adding to that complication, there have been even more on changes on `nsidc:master` since you created this pull request.

I rebased your change onto `nsidc:master` and applied the RuboCop and unit test fixes (which turned out to be simpler than I was expecting) and created #142.

**Pull request closed without merging**
