### PR TITLE
Add ability to set cpu and memory reservations

### PR DESCRIPTION
**Pull request by edmcman**
Add the ability to set reservations from Vagrant.

### CODE REVIEW

**Comment by edmcman** [comment]
Do you have any advice on how to refactor this so it doesn't cause robocop warnings?  The changes I make are tiny, but happen to push several complexity indicators over their limits.

**Comment by michaeljb** [comment]
Well we don't have much actually set in `.rubocop.yml`; the complexity settings are all in `.rubocop_todo.yml`. It would take some serious refactoring to get the whole project down to RuboCop's defaults, and I agree that your changes here are pretty tiny.

I think it'd be fine if you just [regenerate the todo file](https://github.com/bbatsov/rubocop#automatically-generated-configuration) and include it in this PR.

**Comment by edmcman** [comment]
Ok, will do!

**Comment by edmcman** [comment]
Finally passing :)

**Comment by michaeljb** [comment]
Looks good, thanks @edmcman!

**Pull request merged**
