### PR TITLE
relax i18n gem restirctions

### PR DESCRIPTION
**Pull request by jmartin-r7**
To allow installation on newer version of vagrant and since this at least the second time this has occurred see #273, remove the upper limit on `i18n` gem. 

Also bump the ruby and bundler version in travis to allow testing with newer gems.

Another option would be to enforce `~> 1.1` to match vagrant current restriction.

### CODE REVIEW

**Comment by jmartin-r7** [comment]
Test failures here should be fixed by #283

**Comment by jmartin-r7** [comment]
@michaeljb do you still maintain this project?  

Landing this and #238 along with releasing a gem would enable latest vagrant installs to work with this plugin.

**Comment by michaeljb** [comment]
@mlaxer88 is now the primary maintainer for this project.

Released in [v1.13.4](https://github.com/nsidc/vagrant-vsphere/releases/tag/v1.13.4). Thanks @jmartin-r7 , apologies for the delay!

**Comment by jmartin-r7** [comment]
Thank you all!

**Pull request merged**
