### PR TITLE
Removes graceful shutdown for VMs

### PR DESCRIPTION
**Pull request by marnovdm**
As we are about to destroy it anyway I don't think it's required to shut it down cleanly.

### CODE REVIEW

**Comment by michaeljb** [comment]
Does `vagrant destroy --force` work for your purposes? I believe the graceful shut down was added in #104. See also the discussion in #103.

**Comment by marnovdm** [comment]
Thanks for the reference to those other issues. If that's "convention" then so be it, though I still don't see the use of gracefully shutting down something you're about to destroy.

Unfortunately, vagrant destroy --force still seems to trigger a graceful shutdown without my patch:

    root@salt001:/srv/salt/vagrant/projects/apm3/.hybrid-projects/test # vagrant destroy --force wrk001.apm.test
    ==> wrk001.apm.test: Attempting graceful shutdown of VM...

**Comment by michaeljb** [comment]
I've added support for the `--force` flag in 82384a0; could you confirm that this works for you?

**Comment by marnovdm** [comment]
Thanks, --force now works as intended! Still don't see a use-case for a graceful shutdown of something you're about to destroy but at least it's now consistent with other providers :)

**Comment by jwbraucher** [comment]
FWIW, destroying a vagrant machine doesn't necessarily destroy all data associated with the application running on that machine. One use-case for a graceful shutdown is that a vagrant machine might be serving data attached to persistent storage, and the shutdown procedure may be important for leaving that storage in a consistent state.

**Pull request closed without merging**
